name: book_recommendation_app
description: A new Flutter project

publish_to: 'none' 

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  
  # Firebase packages
  firebase_core: ^3.0.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0 

  # HTTP for Google Books API
  http: ^1.2.0

  # OpenAI API
  dio: ^5.0.0

  # Image picker (for profile picture)
  image_picker: ^1.0.4 

  # State management
  provider: ^6.0.0

  # For nice UI
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.jpg
